# Generated by Django 3.2.5 on 2021-09-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=144)),
                ('form', models.CharField(choices=[('FORM-1', 'FORM-1'), ('FORM-2', 'FORM-2'), ('FORM-3', 'FORM-3'), ('FORM-4', 'FORM-4')], max_length=10)),
                ('description', models.TextField()),
                ('term', models.CharField(choices=[('TERM-1', 'TERM-1'), ('TERM-2', 'TERM-2'), ('TERM-3', 'TERM-3')], max_length=10)),
            ],
        ),
    ]
